m = int(input ("Principal: "))
air = float(input("Annual Interest Rate: "))
p = int(input("Period(Years): "))
n = (p * 12)
mir = (air / 12)
r2 = (mir * (1 + mir))
div1 = (r2 * n * n)
div2 = ((1 + mir) * n * n - 1)
mulnum = (div1 / div2)
mort = (m * mulnum)
print("Mortgage: ", mort)
